### PR TITLE
Issue #556 - string padding

### PR DESCRIPTION
**Pull request by abrathovde**
`pad` function accomplishes left and right padding. Determination of left or right padding is facilitated through the order of parameters.

For left padding, the padding width is before the source string.
```
=pad('X', 10, 'fox')
```
Output
`XXXXXXXfox`

For right padding, the padding width is after the source string.
```
=pad('X', 'fox', 10)
```
Output
`foxXXXXXXX`

### CODE REVIEW

**Comment by milosimpson** [comment]
@abrathovde 

Two things.
1) Can you squash all the commits please?
2) Can you please break it up into a "leftPad" and a "rightPad".    While a single "pad" function that can do both is clever, I think it will be more legible for people to explicitly have "left" and "right" versions of them.

**Comment by milosimpson** [comment]
I squashed and rebased this into a single commit over here https://github.com/bazaarvoice/jolt/pull/587  

Will break it into left and right pad, and augment the tests more tomorrow.

**Comment by abrathovde** [comment]
@milosimpson 

Kept `pad`. Extended it to create `leftPad` and `rightPad`. Best of both worlds. What do you think?

**Comment by milosimpson** [comment]
If there is a "rightPad" and a "leftPad" and also a "pad" then would think that "pad" is not just the same thing as right or left, but both.

I.e. in this scenario, I would expect to be able to pad the left and right sides at the same time, which is weird.

**Comment by abrathovde** [comment]
I see your point.

Do you think that the naming is just off? Or the ordering of parameters should not have an impact on the functionality of the operation?

**Comment by milosimpson** [comment]
All the params to a function can come from "@(1,x)" lookups, i.e. the filler, amount to pad, and the string can all be pulled from data from the document.

In that scenario, having the behavior change based on the types of objects is weird.

Also, when reading a spec file, it is nice to easily know "exactly" what a particular function is trying to do.

**Comment by abrathovde** [comment]
I thought that was intended behavior because of the generic/dynamic list of arguments? If not, I was mistaken to assume as much.

Yesterday you mentioned that you would separate `pad` into `leftPad` and `rightPad`. It's an easy enough change for me to do unless you have already started work.

**Comment by milosimpson** [comment]
I have already started work on it / done the work of squashing everything down to a single commit.

Also, going to re-arrange the params

leftPad(  sourceString, integer, padCharacter )

The idea of putting sourceString first is that there is some precendent for having the first param of a function default to the the thing is currently match against, and I would like to be able to do that in the future with the pad functions.


Aka these do the same thing
```
"x" : "=abs(@(1,x))"  and
"x" : "=abs"    
```

**Comment by abrathovde** [comment]
Sounds good. 

Final question... I noticed the last release was back in 2016. With 28+ commits since the last release, what's release plan for 0.1.1?

**Comment by milosimpson** [comment]
Getting leftPad, rightPad and "trim" in then cutting a release.

**Comment by abrathovde** [comment]
Great. Looking forward to it.

**Comment by milosimpson** [comment]
Consolidated and and augmented in  #587.

**Comment by milosimpson** [comment]
@abrathovde Jolt 0.1.1 was just cut and released via maven central.

**Pull request closed without merging**
