### PR TITLE
Would like to add a Convertr operation

### PR DESCRIPTION
**Pull request by chushi**
I have implemented a Convertr operation which allows conversion between types. The logic is similar to Defaultr. It will traverse all JSON object and will allow conversion of types between STRING, INT, FLOAT and BOOLEAN.

### CODE REVIEW

**Comment by milosimpson** [comment]
So thank you for the pull request.

Couple of things 
1. FLOAT should really be DOUBLE, cause that is actually the conversion that is being done, and the "real JavaScript JSON" is doubles and not floats.
2. Would be good to add some more unit tests, specifically walking further down a tree of input data, and using the the "*' wildcard in maps and array.
3. Typically none of the stock Jolt transforms throw TransformExceptions, the ethos of Jolt is that it does what it can, but does not stop in it's tracks.
A way to do that would be to specialize the Convertr methods.  
I.e. STRING, INT, DOUBLE and BOOLEAN will not throws Exceptions if they can't converts, but
STRICT_STRING, STRICT_INT, STRICT_DOUBLE and STRICT_BOOLEAN would.
4. There is a lot of copied code, when really all that is being done it to change the ArrayKey and MapKey.applyLiteralKeyToContainer methods.    If those were made protected, you could subclass Convertr versions of those classes.
That does mean modifying of the Key.parseSpec and processSpec methods, ideally change them so that they are passed a Factory so they can get the appropriate ArrayKey and MapKey subclasses.

**Comment by chushi** [comment]
Thank you for the comments. I will try to fix them and issue the pull request again.

**Comment by milosimpson** [comment]
Hows it going?

**Comment by chushi** [comment]
I didn't have time to work on it during the wee. but I will work on it over the weekend.

**Comment by chushi** [comment]
I have made some changes per your comments. For the comment 4, I am not sure what is the best way to inherit. The Key is in defaultr, and I need to change its constructor to add property type.
Can you verify whether everything else is good and we can discuss more about how to best structure the code. Thanks.

**Comment by dan-frohlich** [comment]
How is this going? I ***need*** this feature!!!

**Comment by milosimpson** [comment]
Closing this pull request, the core features that this provides are not included in the new Modify transform in Jolt 0.0.22.

**Pull request closed without merging**
