### PR TITLE
Split

### PR DESCRIPTION
**Pull request by srilumpa**
Hi,

Can you consider this pull request? It implements the split function in the "modify" operator that will take as parameter a separator (fixed string or regular expression) and a string in the JSON document. The result will be an array containing each substring delimited by the separator. If the separator is not found, it will generate an array of one element which will be the original string. This works basically as the Java `String#split()` function.

I also added the associated unit and feature tests.

Best regards

### CODE REVIEW

**Comment by srilumpa** [comment]
This should cover the use case described in #371

**Comment by milosimpson** [comment]
Nice. I will look at it.

**Comment by milosimpson** [comment]
I have removed the feature.   It "broke" the maven dependency logic of Jolt.   I.e.   "jolt-core" should not have any runtime dependencies on Jackson.    The split functionality required Jackson.

**Comment by milosimpson** [comment]
Sorry, I was thinking of the wrong feature.   "=split" is fine, and has been merged in, and had some additional work done on it.   It will be release in the next version of Jolt.

I was thinking of the "Json Stringify" function.

**Pull request merged**
